# Generated by Django 4.0.1 on 2022-01-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impurities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impurity_id', models.PositiveSmallIntegerField(verbose_name='id примеси согласно pogoda-sv.ru')),
                ('impurity_name', models.CharField(max_length=50, verbose_name='имя примеси')),
                ('conlimit', models.PositiveIntegerField(verbose_name='ПДКм.р.')),
                ('dangerclass', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='класс опасности')),
            ],
        ),
        migrations.CreateModel(
            name='ImpuritiesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('value_st', models.FloatField(verbose_name='Значение в мг/м3')),
                ('value_pdk', models.PositiveSmallIntegerField(verbose_name='Значение в процентах от ПДК')),
                ('impurity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollution_app.impurities')),
            ],
        ),
    ]
