# Generated by Django 4.0.1 on 2022-01-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impurities',
            name='conlimit',
            field=models.FloatField(verbose_name='ПДКм.р.'),
        ),
    ]
