# Generated by Django 4.0.1 on 2022-01-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0002_alter_impurities_conlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpurityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('value_st', models.FloatField(verbose_name='Значение в мг/м3')),
                ('value_pdk', models.PositiveSmallIntegerField(verbose_name='Значение в процентах от ПДК')),
            ],
        ),
        migrations.RenameModel(
            old_name='Impurities',
            new_name='Impurity',
        ),
        migrations.DeleteModel(
            name='ImpuritiesData',
        ),
        migrations.AddField(
            model_name='impuritydata',
            name='impurity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollution_app.impurity'),
        ),
    ]
